// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYwJ8YkulaqGjoUm3YkUz1yTEFseYreFw',
    appId: '1:850890787733:web:32746b2158462712e7c49c',
    messagingSenderId: '850890787733',
    projectId: 'fluttertest-23551',
    authDomain: 'fluttertest-23551.firebaseapp.com',
    databaseURL: 'https://fluttertest-23551-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-23551.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKX-tITzOvoliSFC3sWSAw4pR9O5oIu4',
    appId: '1:850890787733:android:7943b145a556d142e7c49c',
    messagingSenderId: '850890787733',
    projectId: 'fluttertest-23551',
    databaseURL: 'https://fluttertest-23551-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-23551.firebasestorage.app',
  );

}