name: "build"

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version-file: pubspec.yaml

      - run: flutter --version
      - run: flutter pub get

      - name: build apk
        run: flutter build apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-?.apk

      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - run: flutter build web --base-href='/${{ env.REPOSITORY_NAME }}/'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
